name: CI

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:
    branches:
      - '**'
  schedule:
    # Tuesday 8am UTC (3am EST)
    - cron: '0 8 * * TUE'


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_image:
          - 'dev-ocaml-4.12-flambda'
          - '8.15'
          - '8.14'
          - '8.13'
          - '8.12'
          - '8.11'
          - '8.10'
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-record-update.opam'
          custom_image: coqorg/coq:${{ matrix.coq_image }}

# See also:
# https://github.com/coq-community/docker-coq-action#readme
# https://github.com/erikmd/docker-coq-github-action-demo
